export const Events = {
  Ready: 'ready',
  Resumed: 'resumed',
  ApplicationCommandPermissionsUpdate: 'applicationCommandPermissionsUpdate',
  AutoModerationActionExecution: 'autoModerationActionExecution',
  AutoModerationRuleCreate: 'autoModerationRuleCreate',
  AutoModerationRuleUpdate: 'autoModerationRuleUpdate',
  AutoModerationRuleDelete: 'autoModerationRuleDelete',
  ChannelCreate: 'channelCreate',
  ChannelUpdate: 'channelUpdate',
  ChannelDelete: 'channelDelete',
  ChannelPinsUpdate: 'channelPinsUpdate',
  ThreadCreate: 'threadCreate',
  ThreadUpdate: 'threadUpdate',
  ThreadDelete: 'threadDelete',
  ThreadListSync: 'threadListSync',
  ThreadMemberUpdate: 'threadMemberUpdate',
  ThreadMembersUpdate: 'threadMembersUpdate',
  GuildCreate: 'guildCreate',
  GuildUpdate: 'guildUpdate',
  GuildDelete: 'guildDelete',
  GuildAuditLogEntryCreate: 'guildAuditLogEntryCreate',
  GuildBanAdd: 'guildBanAdd',
  GuildBanRemove: 'guildBanRemove',
  GuildEmojisUpdate: 'guildEmojisUpdate',
  GuildStickersUpdate: 'guildStickersUpdate',
  GuildIntegrationsUpdate: 'guildIntegrationsUpdate',
  GuildMemberAdd: 'guildMemberAdd',
  GuildMemberRemove: 'guildMemberRemove',
  GuildMemberUpdate: 'guildMemberUpdate',
  GuildMembersChunk: 'guildMembersChunk',
  GuildRoleCreate: 'guildRoleCreate',
  GuildRoleUpdate: 'guildRoleUpdate',
  GuildRoleDelete: 'guildRoleDelete',
  GuildScheduledEventCreate: 'guildScheduledEventCreate',
  GuildScheduledEventUpdate: 'guildScheduledEventUpdate',
  GuildScheduledEventDelete: 'guildScheduledEventDelete',
  GuildScheduledEventUserAdd: 'guildScheduledEventUserAdd',
  GuildScheduledEventUserRemove: 'guildScheduledEventUserRemove',
  IntegrationCreate: 'integrationCreate',
  IntegrationUpdate: 'integrationUpdate',
  IntegrationDelete: 'integrationDelete',
  InteractionCreate: 'interactionCreate',
  InviteCreate: 'inviteCreate',
  InviteDelete: 'inviteDelete',
  MessageCreate: 'messageCreate',
  MessageUpdate: 'messageUpdate',
  MessageDelete: 'messageDelete',
  MessageDeleteBulk: 'messageDeleteBulk',
  MessageReactionAdd: 'messageReactionAdd',
  MessageReactionRemove: 'messageReactionRemove',
  MessageReactionRemoveAll: 'messageReactionRemoveAll',
  MessageReactionRemoveEmoji: 'messageReactionRemoveEmoji',
  PresenceUpdate: 'presenceUpdate',
  StageInstanceCreate: 'stageInstanceCreate',
  StageInstanceUpdate: 'stageInstanceUpdate',
  StageInstanceDelete: 'stageInstanceDelete',
  TypingStart: 'typingStart',
  UserUpdate: 'userUpdate',
  VoiceStateUpdate: 'voiceStateUpdate',
  VoiceServerUpdate: 'voiceServerUpdate',
  WebhooksUpdate: 'webhooksUpdate'
};


const rawIntents = {
  Guilds: 1 << 0,
  GuildMembers: 1 << 1,
  GuildBans: 1 << 2,
  GuildEmojisAndStickers: 1 << 3,
  GuildIntegrations: 1 << 4,
  GuildWebhooks: 1 << 5,
  GuildInvites: 1 << 6,
  GuildVoiceStates: 1 << 7,
  GuildPresences: 1 << 8,
  GuildMessages: 1 << 9,
  GuildMessageReactions: 1 << 10,
  GuildMessageTyping: 1 << 11,
  DirectMessages: 1 << 12,
  DirectMessageReactions: 1 << 13,
  DirectMessageTyping: 1 << 14,
  MessageContent: 1 << 15,
  GuildScheduledEvents: 1 << 16,
  AutoModerationConfiguration: 1 << 20,
  AutoModerationExecution: 1 << 21
};

export const Intents = {
  ...rawIntents,
  All: Object.values(rawIntents).reduce((a, b) => a | b, 0)
};

export const ActivityType = {
	Playing: 0,
	Streaming: 1,
	Listening: 2,
	Watching: 3,
	Custom: 4,
};
